// <auto-generated />
using GraphQL_ASPNET_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQL_ASPNET_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GraphQL_ASPNET_API.Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Germany",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Germany",
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 5,
                            Country = "France",
                            Name = "Citroen"
                        });
                });

            modelBuilder.Entity("GraphQL_ASPNET_API.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            HorsePower = 350,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/n/cw/ec/50723/m5-exterior-rear-view.jpeg",
                            Model = "M5",
                            ReleaseYear = 2020
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            HorsePower = 400,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/cw/ec/28286/BMW-X7-Rear-view-145752.jpg",
                            Model = "X7",
                            ReleaseYear = 2022
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            HorsePower = 500,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/n/cw/ec/93821/exterior-right-front-three-quarter.jpeg",
                            Model = "Model S",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            HorsePower = 300,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/n/cw/ec/53123/tiguan-exterior-left-front-three-quarter.jpeg",
                            Model = "Tiguan",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 4,
                            HorsePower = 400,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/n/cw/ec/32951/cayenne-exterior-right-rear-three-quarter.jpeg",
                            Model = "Cayenne",
                            ReleaseYear = 2018
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            HorsePower = 700,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/n/cw/ec/45063/porsche-taycan-right-rear-three-quarter0.jpeg",
                            Model = "Taycan",
                            ReleaseYear = 2022
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            HorsePower = 200,
                            ImageUrl = "https://imgd.aeplcdn.com/1056x594/n/cw/ec/103611/c3-exterior-left-rear-three-quarter.jpeg",
                            Model = "C3",
                            ReleaseYear = 2015
                        });
                });

            modelBuilder.Entity("GraphQL_ASPNET_API.Data.Models.Car", b =>
                {
                    b.HasOne("GraphQL_ASPNET_API.Data.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("GraphQL_ASPNET_API.Data.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
